name: Deploy Infrastructure As Code

on:
  workflow_dispatch:
    inputs:
        appenv:
          type: choice
          description: Choose the target environment
          options: 
            - dev
            - test
            - prod

env:
    dev: "dev"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            pages: write
            id-token: write
        steps:
        # Step 1: Checkout the code
        - name: Checkout code
          uses: actions/checkout@main
        
        # Step2: Login To Azure
        - name: Login to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Step 4: Deploy Arm Template
        - name: Deploy ARM Template
          uses: Azure/arm-deploy@v1
          with:
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            resourceGroupName: rg-techexcel
            template: ./InfrastructureAsCode/main.bicep
            parameters: environment=${{ github.event.inputs.appenv }} #environment=${{ env.dev }}
            deploymentMode: 'Incremental'


