name: Deploy App - Dev

on:
  workflow_dispatch:

env:
    dev: "dev"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            pages: write
            id-token: write
        steps:
        # Step 1: Checkout the code
        - name: Checkout code
          uses: actions/checkout@main
        
        # Step2: Login To Azure
        - name: Login to Azure
          uses: azure/login@v1
          with:
            ClientId: ${{ secrets.AZURE_CLIENT_ID }}
            tenantId: ${{ secrets.AZURE_TENANT_ID }}
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            enable-AzPSSession: true

        # Step 4: Deploy Arm Template
        - name: Deploy ARM Template
          uses: Azure/arm-deploy@v1
          with:
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            resourceGroupName: rg-techexcel
            template: ./InfrastructureAsCode/main.bicep
            parameters: environment=${{ env.dev }}
            deploymentMode: 'Incremental'


