name: First Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Step 1 complete!"
      - name: step2
        run: echo "Step 2 complete!"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Cowsays
        uses: mszostok/cowsay-action@v2
        with:
          text: "Ready for prod–ship it!"
          color: "magenta"