name: First Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened]

env:
  text1: "Step 1 complete!"
  text2: "Step 2 complete!"
  cowsay_text: "Ready for prod–ship it!"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo ${{ env.text1 }}
      - name: step2
        run: echo ${{ env.text2 }}

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Cowsays
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: ${{ env.cowsay_text }}
          color: "magenta"